# Generated by Django 3.2 on 2021-04-19 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('note', models.CharField(max_length=300)),
                ('create_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-create_date_time'],
                'default_permissions': (),
            },
        ),
    ]
